-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  ip_address inet,
  user_agent text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.educations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  degree text NOT NULL,
  field_of_study text,
  institution text NOT NULL,
  location text,
  graduation_date date,
  gpa text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT educations_pkey PRIMARY KEY (id),
  CONSTRAINT educations_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.feature_flags (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  flag_name character varying NOT NULL UNIQUE,
  description text,
  is_enabled boolean DEFAULT false,
  rollout_percentage integer DEFAULT 0 CHECK (rollout_percentage >= 0 AND rollout_percentage <= 100),
  enabled_for_tiers ARRAY,
  enabled_for_users ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT feature_flags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['profile_view'::character varying, 'resume_view'::character varying, 'resume_download'::character varying, 'resume_share'::character varying, 'new_follower'::character varying, 'resume_like'::character varying, 'resume_comment'::character varying, 'mention'::character varying, 'system_announcement'::character varying, 'milestone_reached'::character varying]::text[])),
  title character varying NOT NULL,
  message text,
  action_url text,
  related_user_id uuid,
  related_resume_id uuid,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_related_user_id_fkey FOREIGN KEY (related_user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_related_resume_id_fkey FOREIGN KEY (related_resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.reserved_usernames (
  username character varying NOT NULL,
  reason text NOT NULL,
  reserved_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reserved_usernames_pkey PRIMARY KEY (username)
);
CREATE TABLE public.resume_comments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resume_id uuid NOT NULL,
  user_id uuid NOT NULL,
  parent_comment_id uuid,
  comment_text text NOT NULL CHECK (char_length(comment_text) >= 1 AND char_length(comment_text) <= 1000),
  is_edited boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resume_comments_pkey PRIMARY KEY (id),
  CONSTRAINT resume_comments_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT resume_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT resume_comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES public.resume_comments(id)
);
CREATE TABLE public.resume_downloads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resume_id uuid NOT NULL,
  downloader_user_id uuid,
  visitor_ip inet,
  visitor_country character varying,
  device_type character varying,
  downloaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resume_downloads_pkey PRIMARY KEY (id),
  CONSTRAINT resume_downloads_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT resume_downloads_downloader_user_id_fkey FOREIGN KEY (downloader_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.resume_likes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resume_id uuid NOT NULL,
  user_id uuid NOT NULL,
  liked_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resume_likes_pkey PRIMARY KEY (id),
  CONSTRAINT resume_likes_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT resume_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.resume_shares (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resume_id uuid NOT NULL,
  user_id uuid NOT NULL,
  share_method character varying NOT NULL CHECK (share_method::text = ANY (ARRAY['email'::character varying, 'linkedin'::character varying, 'twitter'::character varying, 'whatsapp'::character varying, 'link_copy'::character varying, 'qr_code'::character varying, 'embed'::character varying]::text[])),
  recipient_email character varying,
  recipient_name character varying,
  share_token uuid DEFAULT uuid_generate_v4(),
  clicks_count integer DEFAULT 0,
  last_clicked_at timestamp with time zone,
  shared_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resume_shares_pkey PRIMARY KEY (id),
  CONSTRAINT resume_shares_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT resume_shares_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.resume_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  name character varying NOT NULL,
  description text,
  category character varying,
  template_data jsonb NOT NULL,
  style_config jsonb NOT NULL,
  preview_image_url text,
  thumbnail_url text,
  is_public boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  is_premium boolean DEFAULT false,
  use_count integer DEFAULT 0,
  like_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resume_templates_pkey PRIMARY KEY (id),
  CONSTRAINT resume_templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.resume_versions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resume_id uuid NOT NULL,
  version_number integer NOT NULL,
  version_name character varying,
  resume_data jsonb NOT NULL,
  template_style character varying,
  color_scheme jsonb,
  pdf_url text,
  thumbnail_url text,
  changed_fields ARRAY,
  change_summary text,
  diff_json jsonb,
  ats_score integer,
  view_count integer,
  created_by_user_id uuid,
  is_autosave boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resume_versions_pkey PRIMARY KEY (id),
  CONSTRAINT resume_versions_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT resume_versions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.resume_views (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resume_id uuid NOT NULL,
  viewer_user_id uuid,
  session_id uuid,
  view_type character varying DEFAULT 'page_view'::character varying,
  visitor_ip inet,
  visitor_fingerprint character varying,
  visitor_country character varying,
  visitor_region character varying,
  visitor_city character varying,
  visitor_timezone character varying,
  visitor_lat numeric,
  visitor_lng numeric,
  user_agent text,
  device_type character varying,
  device_brand character varying,
  device_model character varying,
  browser character varying,
  browser_version character varying,
  os character varying,
  os_version character varying,
  screen_resolution character varying,
  referrer text,
  referrer_domain character varying,
  utm_source character varying,
  utm_medium character varying,
  utm_campaign character varying,
  utm_term character varying,
  utm_content character varying,
  time_on_page integer,
  scroll_depth_percentage integer,
  clicks_on_page integer DEFAULT 0,
  clicked_contact boolean DEFAULT false,
  clicked_linkedin boolean DEFAULT false,
  clicked_github boolean DEFAULT false,
  clicked_download boolean DEFAULT false,
  viewed_at timestamp with time zone DEFAULT now(),
  session_started_at timestamp with time zone,
  session_ended_at timestamp with time zone,
  CONSTRAINT resume_views_pkey PRIMARY KEY (id),
  CONSTRAINT resume_views_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT resume_views_viewer_user_id_fkey FOREIGN KEY (viewer_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.resumes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  slug character varying NOT NULL CHECK (slug::text ~ '^[a-z0-9-]+$'::text),
  title character varying NOT NULL,
  description text,
  resume_data jsonb NOT NULL,
  country character varying NOT NULL,
  language character varying NOT NULL DEFAULT 'English'::character varying,
  template_style character varying NOT NULL DEFAULT 'professional'::character varying,
  color_scheme jsonb,
  font_family character varying DEFAULT 'Calibri'::character varying,
  pdf_url text,
  pdf_file_size bigint,
  pdf_version integer DEFAULT 1,
  html_content text,
  thumbnail_url text,
  thumbnail_large_url text,
  visibility character varying DEFAULT 'public'::character varying CHECK (visibility::text = ANY (ARRAY['public'::character varying, 'private'::character varying, 'unlisted'::character varying]::text[])),
  is_default boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  password_protected boolean DEFAULT false,
  password_hash text,
  allowed_domains ARRAY,
  meta_title character varying,
  meta_description text,
  og_image_url text,
  tags ARRAY,
  keywords ARRAY,
  ats_score integer CHECK (ats_score IS NULL OR ats_score >= 0 AND ats_score <= 100),
  readability_score integer,
  keyword_optimization_score integer,
  last_optimization_at timestamp with time zone,
  view_count integer DEFAULT 0,
  unique_view_count integer DEFAULT 0,
  download_count integer DEFAULT 0,
  share_count integer DEFAULT 0,
  last_viewed_at timestamp with time zone,
  version_number integer DEFAULT 1,
  parent_resume_id uuid,
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  search_vector tsvector,
  CONSTRAINT resumes_pkey PRIMARY KEY (id),
  CONSTRAINT resumes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT resumes_parent_resume_id_fkey FOREIGN KEY (parent_resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.schema_migrations (
  version character varying NOT NULL,
  description text,
  applied_at timestamp with time zone DEFAULT now(),
  CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);
CREATE TABLE public.user_follows (
  follower_id uuid NOT NULL,
  following_id uuid NOT NULL,
  followed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_follows_pkey PRIMARY KEY (follower_id, following_id),
  CONSTRAINT user_follows_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES public.users(id),
  CONSTRAINT user_follows_following_id_fkey FOREIGN KEY (following_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_profile_views (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_user_id uuid NOT NULL,
  viewer_user_id uuid,
  visitor_ip inet,
  visitor_country character varying,
  visitor_city character varying,
  device_type character varying,
  browser character varying,
  referrer text,
  viewed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profile_views_pkey PRIMARY KEY (id),
  CONSTRAINT user_profile_views_profile_user_id_fkey FOREIGN KEY (profile_user_id) REFERENCES public.users(id),
  CONSTRAINT user_profile_views_viewer_user_id_fkey FOREIGN KEY (viewer_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  full_name text,
  email text,
  phone text,
  city text,
  country text,
  linkedin_url text,
  photo_url text,
  professional_summary text,
  skills jsonb DEFAULT '[]'::jsonb,
  languages jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  auth_user_id uuid NOT NULL UNIQUE,
  username character varying NOT NULL UNIQUE CHECK (username::text ~ '^[a-z0-9_-]+$'::text),
  email character varying NOT NULL UNIQUE CHECK (email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  full_name character varying NOT NULL,
  display_name character varying,
  avatar_url text,
  cover_image_url text,
  bio text,
  headline character varying,
  location character varying,
  timezone character varying DEFAULT 'UTC'::character varying,
  website_url text,
  linkedin_url text,
  github_url text,
  twitter_url text,
  portfolio_url text,
  profile_visibility character varying DEFAULT 'public'::character varying,
  default_resume_id uuid,
  preferred_language character varying DEFAULT 'en'::character varying,
  preferred_country character varying,
  email_notifications boolean DEFAULT true,
  is_email_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  is_suspended boolean DEFAULT false,
  suspension_reason text,
  onboarding_completed boolean DEFAULT false,
  onboarding_step integer DEFAULT 0,
  account_tier character varying DEFAULT 'free'::character varying,
  resumes_count integer DEFAULT 0,
  resumes_limit integer DEFAULT 10,
  storage_used_bytes bigint DEFAULT 0,
  storage_limit_bytes bigint DEFAULT 104857600,
  total_profile_views integer DEFAULT 0,
  total_resume_views integer DEFAULT 0,
  total_resume_downloads integer DEFAULT 0,
  last_login_at timestamp with time zone,
  last_active_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  search_vector tsvector,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT fk_users_default_resume FOREIGN KEY (default_resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.work_experiences (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  job_title text NOT NULL,
  company text NOT NULL,
  location text,
  start_date date NOT NULL,
  end_date date,
  is_current boolean DEFAULT false,
  achievements ARRAY DEFAULT '{}'::text[],
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT work_experiences_pkey PRIMARY KEY (id),
  CONSTRAINT work_experiences_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.user_profiles(id)
);
